repos:
# general checker
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-toml

# Python - code formatter
- repo: "https://github.com/psf/black"
  rev: "23.7.0"
  hooks:
  - id: "black"

# Python - imports sorter
- repo: "https://github.com/pycqa/isort"
  rev: "5.12.0"
  hooks:
  - id: "isort"
    args:
    - "--profile=black"

# Python - linter
- repo: "https://github.com/pycqa/flake8.git"
  rev: "6.1.0"
  hooks:
  - id: "flake8"
