name: 'CI Tests'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}-ci
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python from .python-version
        uses: actions/setup-python@v5

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
